---
require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-thread_safety

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  DisplayStyleGuide: true
  Exclude:
    - bin/**/*
    - db/**/*
    - spec/cache/**/*
    - tmp/**/*

Layout/LineLength:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - spec/**/*

Lint/UnreachableCode:
  Exclude:
    - app/concepts/**/operation/**

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Naming/MethodName:
  Exclude:
    - app/concepts/**/macro/**

Naming/VariableNumber:
  EnforcedStyle: snake_case
  Exclude:
    - config/routes.rb

Rails:
  Enabled: true

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - production

RSpec/DescribeClass:
  Exclude:
    - spec/requests/**/*

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NamedSubject:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SignalException:
  Exclude:
    - app/concepts/**/operation/**
