Metrics/LineLength:
  Enabled: false

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Send:
  Enabled: true

Style/SymbolArray:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'doc/**/*'
    - 'db/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
